### ISSUE TITLE
Support Mermaid

### ISSUE THREAD

**Issue by fuelen** [fuelen/ecto_erd#15]
https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/
https://mermaid-js.github.io/mermaid/#/classDiagram

**Comment by cw789** [comment]
They do - but there are some limitations.
> The `type` and `name` values must begin with an alphabetic character and may contain digits, hyphens or underscores. Other than that, there are no restrictions, and there is no implicit set of valid data types.

**Comment by fuelen** [comment]
Anyway, the biggest blocker for this feature is how ERD is rendered in examples by the link above
![image](https://user-images.githubusercontent.com/588762/154819749-78d0b861-92dd-4d48-8a71-6ac567a451c9.png)

**Comment by fuelen** [comment]
Seems like rendering is fixed 
![зображення](https://user-images.githubusercontent.com/588762/168768306-06d3d0f8-e132-461a-bb3e-69ff90a1d33e.png)
