### ISSUE TITLE
Include database indexes in the ERD

### ISSUE THREAD

**Issue by yoonwaiyan** [fuelen/ecto_erd#28]
Hi there, thanks for the great work on this library!

Apart from supporting Mermaid generation which from my understanding it's currently work in progress, I would like to also make a request to support the inclusion of database indexes in the ERD 🙏

**Comment by fuelen** [comment]
Hi @yoonwaiyan 

Thank you for the suggestion, but such feature is not possible to implement, as information about database indexes is not defined in Ecto schemas.
