### ISSUE TITLE
Is it possible to pretty-print the Graphviz / dot output (including HTML inside)?

### ISSUE THREAD

**Issue by nivertech** [fuelen/ecto_erd#5]
Usecase: I have a Github Action which runs `ecto_erd` on each merged PR.
That way I can see clear diffs in ecto schemas and whether this PR changed schemas at all.
It's easy to pretty-print Graphviz DSL, but unfortunatelly the HTML inside is still one big unformulated blob.

Two ways to pretty-print Graphviz:
- `nop http://myfile.dot` (https://graphviz.org/pdf/nop.1.pdf)
- `dot -Tcanon http://myfile.dot` (https://graphviz.org/docs/outputs/canon/)

**Comment by fuelen** [comment]
hey @nivertech 
I'm afraid that formatting HTML is not really possible, as HTML engine in Graphviz is sensitive to multiple spaces
